### ISSUE TITLE
Did reference ×1024+ needs Pro?

### ISSUE THREAD

**Issue by MikeTaunt** [hippogamesunity/PixelStudioHub#101]
Okay, I use this app for many years...
Did reference which have more than 1024×1024 required Pro now? Before isn't? I want to draw some art as pokemon style but now can't because I can't add reference...

**Comment by hippogamesunity** [comment]
Hello! No, the limit shouldn't apply to reference. I'll check this, thanks for reporting.

**Comment by MikeTaunt** [comment]
Oh yea, it's fixed now, thanks for hearing me
