### ISSUE TITLE
Bug: Canceling the import image process on MacOS causes the app to crash

### ISSUE THREAD

**Issue by StereoMadnessss** [hippogamesunity/PixelStudioHub#104]
There is this weird bug where if you are making an image and then decide to import an image externally and then in the finder file picker window click cancel, the app will crash.
Video of that, 540p to reduce file size:

https://user-images.githubusercontent.com/77188051/147974882-088d32f0-27c8-4400-8884-91e03765d459.mp4

The last section where my browser shows signifies a crash. I have only tested this on MacOS. Try what I did on other versions of the app and let me know if this bug affects all versions.

**Comment by hippogamesunity** [comment]
Hi, it's a known issue in 3rd party component (File Browser). Unfortunately, it's no longer supported, so this can't be fixed.
