### ISSUE TITLE
Password reset (and creating new account) shows HTTP Error

### ISSUE THREAD

**Issue by ammerhai** [hippogamesunity/PixelStudioHub#105]
Tried to reset my account password with username  and email. In both cases I got the HTTP/1.1 500 Internal Server Error. 
I didn't get any reset mail or something else to reset. I used Steam, Android and the Microsoft Store Version but the same issue happens at all platforms.
So i created a new account to test it again with a password I had not lost and after finishing the same error showed up, but the account was created.

**Comment by hippogamesunity** [comment]
Hello! The reason is "Service invoked too many times for one day: email.". I've added a reserved email service. I'll also add timeout for client apps.
You can try again, it should work now.
