### ISSUE TITLE
Не открывает настройки пера

### ISSUE THREAD

**Issue by damanickfisher** [hippogamesunity/PixelStudioHub#106]
Я рисую только пером S Pen, стандарт для плашета Samsung SM-P610. До сегодняшнего дня в приложении была отключена возможность нарисовать что-либо рукой. Сегодня не реагировала нижняя панель инструментов и позже приложение снова начало видеть руку. Для меня это крайне неудобно. Настройки пера не открываются, я не могу заново настроить только касание пера. Перо видит, с этим проблеи нет.

**Comment by damanickfisher** [comment]
> Я рисую только пером S Pen, стандарт для плашета Samsung SM-P610. До сегодняшнего дня в приложении была отключена возможность нарисовать что-либо рукой. Сегодня не реагировала нижняя панель инструментов и позже приложение снова начало видеть руку. Для меня это крайне неудобно. Настройки пера не открываются, я не могу заново настроить только касание пера. Перо видит, с этим проблем нет.

**Comment by hippogamesunity** [comment]
Привет, версия 3.82?

**Comment by damanickfisher** [comment]
> Привет, версия 3.82?

3.81
о, есть свежая версия? Я обновлюсь и отпишусь о результате

**Comment by damanickfisher** [comment]
СПАСИБИЩЕ!!! обновление меня спасло!!! Обожаю ваше приложение :)

**Comment by hippogamesunity** [comment]
Бывают косяки с обновлениями, все равно спасибо за сообщения!
