### ISSUE TITLE
Problem with S-Pen

### ISSUE THREAD

**Issue by solko12** [hippogamesunity/PixelStudioHub#107]
Hi!
Since last update I have problem with using spen in pixel studio. It looks like samsung spen and finger touch changed working way each other.

**Comment by hippogamesunity** [comment]
Hello! Do you use the 3.83 version? If so, whats's the problem?

**Comment by solko12** [comment]
Yes, I'm using that version.
Basically s-pen doesn't work properly in the app.  In the s-pen settings in the application, I select enable Samsung spen and select "Action on finger touch" on Move.  And touched with spen, the screen moves, and when touched with your finger, it draws.

**Comment by hippogamesunity** [comment]
Do you have another phone to make a video? Please, as I can't reproduce it on may tab s6.

**Comment by solko12** [comment]
Here you go

https://user-images.githubusercontent.com/62014585/149288543-fe1beee3-c5e2-4f5d-8989-3cd56cd9c679.mp4

**Comment by hippogamesunity** [comment]
Hello, do you use Discord? So we could continue online.

**Comment by hippogamesunity** [comment]
Basically, I have a test tracking utility https://play.google.com/store/apps/details?id=com.UnityInputTest
Could you install it and make a video of touching the screen with fingers and S-Pen?

**Comment by solko12** [comment]
Hi, that is video with tool.
https://user-images.githubusercontent.com/62014585/149526883-5e221a89-c480-4ea3-8414-0bc20950018b.mp4

**Comment by hippogamesunity** [comment]
Many thanks! Yes, for some reason youк finger is tracked as Touchscreen1 and the pen as Touchscreen, while normally it's vice versa. It's enough for me to make a hotfix, a new update will be available soon (3.84).

**Comment by solko12** [comment]
Okay, thanks a lot!! I look forward to this update!

**Comment by hippogamesunity** [comment]
Hello, please try 3.84 and let me know if it's fixed.

**Comment by solko12** [comment]
Yeah, works perfect! Thanks a lot, your app is the best!

**Comment by hippogamesunity** [comment]
Thanks for your time!
