### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by DrChefTetra** [hippogamesunity/PixelStudioHub#111]
You see I'm trying to save my art. but I can't because when I press save my cursor does the rainbow ring thing and when I check for the app to see if its responding it says that it isn't responding.I don't know if I did something or its the apps fault. If any one could help me figure out this problem that would be wonderful. Thank you

**Comment by hippogamesunity** [comment]
thanks for reporting. please update your MacOS to the latest version if it's possible (12.0.1). I can confirm that it works onMacOS Monterey. If you can't update as a workaround you can open menu - click on three dots near the Save button and then choose Storage destination. Your image will be saved to the Pictures folder.

**Comment by DrChefTetra** [comment]
Thanks for the tip I was able to save my art work. thank you so much.
