### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Toonjunki** [hippogamesunity/PixelStudioHub#112]
I just downloaded PixelStudio from the App Store. When I open it, I see the PixelStudio logo, then it just fades to black and that’s all I get.

**Comment by hippogamesunity** [comment]
Hi, does it iOS on Mac?

**Comment by BSCNFTs** [comment]
I updated yesterday and I have same issue with IPhone app.

**Comment by yafarida** [comment]
@BSCNFTs @Toonjunki hi! Thanks for reporting. Please make a back up of all your works and reinstall the app. If the issue repeats please let me know your iPhone model and iOS version. Thanks!

**Comment by hooverfocus** [comment]
I also downloaded it from the App store. Right now I'm confused, is it meant to work on a computer at all? I'm on macOS 10.13. I'm having the same issue as the original poster, if I launch the app it just doesn't... it crashes upon trying to open.

**Comment by hippogamesunity** [comment]
Hi, are you on M1 or Intel?

**Comment by hooverfocus** [comment]
> 

Intel.
I'd gladly settle for an older supported base version but it can't be found anywhere.

**Comment by hippogamesunity** [comment]
Can you confirm that the last version from the Mac App Store doesn't work with Intel cpu? Did you try updating Mac OS to the latest possible version? Unfortunately, I have only the latest M1 device, it it may take time to get Intel for test purposes.

**Comment by hooverfocus** [comment]
The latest version (as of yesterday at least) from the App store doesn't work on macOS 10.13 with Intel CPU. Unfortunately I cannot update that laptop to the latest macOS as it's not supported.
Cheers for trying, though!
Would you consider making older versions available?

**Comment by hooverfocus** [comment]
FYI I got a notification that a new version was available in the App Store so I updated it (the one I could never get to launch/open), and now it works fine!

**Comment by hippogamesunity** [comment]
Thanks for confirming! Yes, I was able to purchase a Mac Mini with Intel CPU to fix the issue =)
