### ISSUE TITLE
Black out

### ISSUE THREAD

**Issue by HitoshiAraki** [hippogamesunity/PixelStudioHub#114]
Updated my pixel art app to 3.89, it doesn't work at ipad mini 5(iOS 15.3). 
After the logo screen, black out and nothing is displayed. 
Do you have any idea?

**Comment by hippogamesunity** [comment]
Hi, did you try reinstalling? Don't forget to make a backup of Pixel Studio
folder.

вс, 30 янв. 2022 г., 10:53 Hitoshi Araki ***@***.***>:

**Comment by HitoshiAraki** [comment]
It's worked!
I tried reinstalling, after the logo screen, then, "Warning!" window has appeared, 
"The app has stopped unexpectedly :( Press [Yes]~~~"
it worked fine! thanks!
