### ISSUE TITLE
Update Android Version (Pro)

### ISSUE THREAD

**Issue by BenHerbst** [hippogamesunity/PixelStudioHub#124]
In the play store are 2 versions, pro and normal, but the pro version is outdated, for some time now, and on previous versions then Android 11 the normal version had all pro features when pro was installed, but now this changed and the normal version has no pro features when pro version is installed but pro has, but the pro app version is outdated and the normal not. Maybe upgrade the pro version to the new Android file system so the normal app can maybe detect that pro version is installed like on < Android 11?

**Comment by hippogamesunity** [comment]
Hello, both versions are 3.91 on Google Play.

вт, 1 мар. 2022 г., 02:16 Ben Herbst ***@***.***>:

**Comment by BenHerbst** [comment]
But the pro version has the old tab ui?
