### ISSUE TITLE
Opening Aseprite file got an error

### ISSUE THREAD

**Issue by me-no** [hippogamesunity/PixelStudioHub#125]
I was trying to open .aseprite file and got an error, so I would like to ask 
if it's just as expected or there is some technical issue. 

I attached the latest log files on iPad, and the screenshot of the error message. 
This message appeared when I chose "open > open from files" and the .aseprite file. 

Should I convert this .aseprite file to some appropriate file format? 
![IMG_2028](https://user-images.githubusercontent.com/100861251/156605904-7b8c1380-5c3c-4bc7-8a24-72748744fcc4.jpg)
[logs.zip](https://github.com/hippogamesunity/PixelStudioHub/files/8179290/logs.zip)

**Comment by hippogamesunity** [comment]
Hello, please attach the .aseprite file!

**Comment by hippogamesunity** [comment]
Hi, any details?

**Comment by me-no** [comment]
Hello, 
Sorry to be late, and I'm afraid I should not upload it since the file is not made by me.  

I confirmed that the same issue happens with Android. 

[error-android.txt](https://github.com/hippogamesunity/PixelStudioHub/files/8187013/error-android.txt)

If there is no possible way to open it, I'll give it up for now.

**Comment by hippogamesunity** [comment]
Ok, good luck!

**Comment by StereoMadnessss** [comment]
I think it was trying to read the wrong file format while it loaded the file, causing an integer overflow leading to pixel studio crashing.
