### ISSUE TITLE
BMP Doesnt actually work

### ISSUE THREAD

**Issue by N8rtot** [hippogamesunity/PixelStudioHub#128]
Importing a BMP file doesnt work, it ends up showing completely blank, and exporting as a BMP isnt listed as an option either, despite being shown here as an option. 
https://github.com/hippogamesunity/PixelStudioHub/wiki/Image-formats

**Comment by hippogamesunity** [comment]
Hello, BMP is supported for Read only. Could you send me your file please?

пт, 11 мар. 2022 г., 02:57 N8rtot ***@***.***>:
