### ISSUE TITLE
Screen Ghosting on iPhone 7

### ISSUE THREAD

**Issue by cavefacts** [hippogamesunity/PixelStudioHub#134]
After using it for about an hour (first time ever), I started to see screen ghosting from the tool menus and the checkerboard background. I closed all the tabs, closed & restarted app, and then finally I deleted & reinstalled app. It's still there. I already bought PRO but I don't think I can keep using the app if this ghosting doesn't go away. It's only in this app, not in my other apps.

**Comment by cavefacts** [comment]
![B714DBCA-96CC-4CD5-ACFE-6FA6E59A41DB](https://user-images.githubusercontent.com/77606013/159927848-5226b808-7623-449f-9d94-d058e4131462.png)

**Comment by hippogamesunity** [comment]
![image](https://user-images.githubusercontent.com/7318172/159960334-e788a49a-f96b-4609-8e7e-40ae35fb3b38.png)

**Comment by hippogamesunity** [comment]
Maybe you mean the function of the button with the EYE icon?

**Comment by cavefacts** [comment]
oh wowwww, it IS my phone, i just couldn't see the ghosting happening in
other apps but once i found another app with a black background, i could
see it.

nevermind. 🤪 i can use your app on my iPad i realized.
