### ISSUE TITLE
Пропало PRO

### ISSUE THREAD

**Issue by RUSLANA1976** [hippogamesunity/PixelStudioHub#135]
Купила ПРО. Поработало 2 дня. Что делать?

**Comment by StereoMadnessss** [comment]
Missing PRO #135

Bought PRO. Worked for 2 days. What to do?

**Comment by hippogamesunity** [comment]
Привет. Вот ссылка на восстановление PRO: https://github.com/hippogamesunity/PixelStudioHub/wiki/Restore-purchases
