### ISSUE TITLE
there is no option to save to .svg 

### ISSUE THREAD

**Issue by JEmerson23** [hippogamesunity/PixelStudioHub#150]
I bought the pro version to be able to save in .svg to use at work, but I don't see the option. 
![Screenshot_20220914-060753_Pixel Studio](https://user-images.githubusercontent.com/92601129/190112165-051dce61-576e-466e-a178-e00c80779f92.jpg)

**Comment by hippogamesunity** [comment]
Hi, right, I'll check if this is possible. Note that svg is a vector
format, while pixel art is not a vector art.

ср, 14 сент. 2022 г., 12:09 Emerson23 ***@***.***>:

**Comment by hippogamesunity** [comment]
Right, the app can only read (rasterize) SVG as advertised.
https://github.com/hippogamesunity/PixelStudioHub/wiki/Image-formats

ср, 14 сент. 2022 г. в 12:19, Hippo Games ***@***.***>:
