### ISSUE TITLE
Google Drive sync doesn't delete files

### ISSUE THREAD

**Issue by fccfc5d245c** [hippogamesunity/PixelStudioHub#151]
- I have 3 devices logged into Drive: Android phone, Android tablet, Windows 10 PC, all files are synced
- in any device, let's say phone, I delete "file1" and tap sync. File1 stays deleted
- in my tablet or PC, I tap sync (expecting to get "file1" deleted), but the device keeps it and uploads a copy to Drive
- back to my phone, I hit sync and I get file1 back

Maybe it's me, but when I delete a file, I expect the file to be removed from the other devices. 

And if I move files to folders, that creates duplicates!

Is this behaviour expected? How could we go about organizing and syncing our files? doing it manually in every device and using sync only to add files? not to delete or move them?

Thank you.

**Comment by fccfc5d245c** [comment]
Thanks a lot! Personally, I don't mind having to tap the sync button, but being able to organize my files in one device and have the others mirror the content of the former, that would save a lot of time.

Should I close the Issue?

**Comment by hippogamesunity** [comment]
I'll do this, thanks.
