### ISSUE TITLE
Сломанное хранилище

### ISSUE THREAD

**Issue by Denyerro** [hippogamesunity/PixelStudioHub#152]
Мое хранилище заполнено на 1700 кб из 2048. Пытаюсь опубликовать гиф на 30 кб. Пишет "очистите место в хранилище или купите премиум", ну, по типу. Я удалил половину своих работ чтобы выложить последнюю. Ничего не поменялось.

**Comment by hippogamesunity** [comment]
Привет, какая версия приложения и какой логин?

**Comment by Denyerro** [comment]
Версия 4.24, Denyerro

**Comment by hippogamesunity** [comment]
Проверю, спасибо!

**Comment by Denyerro** [comment]
И вам

**Comment by hippogamesunity** [comment]
Исправлено в 4.25, скоро выйдет.
