### ISSUE TITLE
Nie mogę kupić wersji pro I can't buy the pro version

### ISSUE THREAD

**Issue by kubixdddd** [hippogamesunity/PixelStudioHub#153]
chciałem kupić sobie wersje pro jednak okienko kupna nie reaguje po kliknięciu muszką a cena nie jest wyświetlana zamiast niej są trzy kropki próbowałem już wszystkiego grzebania w ustawieniach czy stworzenie sobie kota lub odinstalowanie aplikacji jak co mam wersje stimową i najgorsze jest to że przed czyszczeniem komputera ten błot nie występował 

I wanted to buy the pro version, but the purchase window does not react after clicking the bow tie and the price is not displayed instead there are three dots I have tried everything in the settings, whether creating a cat or uninstalling the application like what I have stim versions and the worst thing is that before cleaning the computer this there was no mud

**Comment by hippogamesunity** [comment]
Hi! Thanks for reporting, I'll try to fix this asap.

**Comment by hippogamesunity** [comment]
Please restart Steam and update the app. The problem should be solved now.

**Comment by kubixdddd** [comment]
no problem anymore thank you very much

**Comment by hippogamesunity** [comment]
You're welcome!
