### ISSUE TITLE
В каком формате сохранять анимацию которая длится больше 20 секунд? 

### ISSUE THREAD

**Issue by SuperPuperDuper** [hippogamesunity/PixelStudioHub#154]
Сделал анимацию. 70 кадров, 22 секунды длится. В каком формате нужно сохранить эту анимацию? Гиф слишком обрезает, mp4 тоже. Ах да! На всякий случай. Я говорю про pixel studio

**Comment by hippogamesunity** [comment]
А в чем конкретно проблема?

**Comment by SuperPuperDuper** [comment]
Не знаю в каком формате сохранять
Формат Gif обрезает, формат mp4 тоже. А мне нужна анимация полностью

**Comment by SuperPuperDuper** [comment]
> @Гиппогеймюнити Не знаю в каком формате сохранять. Формат Gif обрезает, формат mp4 тоже. А мне нужна анимация полностью

**Comment by hippogamesunity** [comment]
Что значит "обрезает"? В приложении нет такой функции.

**Comment by SuperPuperDuper** [comment]
@hippogamesunity
Обрезает
То есть видео короче самой анимации

**Comment by hippogamesunity** [comment]
Пришлите видео и анимацию, посмотрим.

**Comment by SuperPuperDuper** [comment]
Проблема решилась сама собой 😓😥
Видимо в первый раз произошёл баг, потому что со второй попытки анимация сохранилась нормально в формате gif
