### ISSUE TITLE
File Extensions are broken after save

### ISSUE THREAD

**Issue by echox** [hippogamesunity/PixelStudioHub#157]
Hi,

tested on MacOS, 4.40 Beta and 4.42 Beta (latest):

If I try to save a file PS will always try to add the file extension "..png" (note the double '.').
If I try to add the extension myself it displays a warning message letting me choose between "png...png" or only "..png".
The problem consists independently of the chosen file type extension.

This is really confusing and forces me to rename all saved files afterwards.
Did I miss something or is this a bug?

<img width="263" alt="Screenshot 2023-01-13 at 13 24 26" src="https://user-images.githubusercontent.com/146484/212325842-bd599ec8-24aa-4c03-95b2-fcc0f0404ea8.png">
<img width="297" alt="Screenshot 2023-01-13 at 13 24 03" src="https://user-images.githubusercontent.com/146484/212325850-46bc31d9-0f2a-46bc-aa3b-8e5122e01416.png">

**Comment by hippogamesunity** [comment]
Hi, I'll check this asap.

**Comment by hippogamesunity** [comment]
Fixed in 4.44
