### ISSUE TITLE
I can't see the picture I drew.

### ISSUE THREAD

**Issue by LetheRegina** [hippogamesunity/PixelStudioHub#159]
Hello. I am Korean. I use a translator.
I can't see my picture on the app. I thought my painting was gone.
But I backed up on Google Drive. I sang Google drive in Google drive, but I don't see the picture. It looks very small number of paintings.
I filmed the process with a video.
I'll send you this video, so please tell me where to send it.
I think the file exists, but it's not visible.

**Comment by LetheRegina** [comment]
Hello. I am Korean. I use a translator.
I can't see my picture on the app. I thought my painting was gone.
But I backed up on Google Drive. I sang Google drive in Google drive, but I don't see the picture. It looks very small number of paintings.
I filmed the process with a video.
I'll send you this video, so please tell me where to send it.
I think the file exists, but it's not visible.

**Comment by hippogamesunity** [comment]
Hi! Make sure you're using the latest version 4.44+.
You can upload the video to Google Drive and share the link.

**Comment by LetheRegina** [comment]
I deleted the app and downloaded it again.But I still don't see my picture. Only 11 files are visible.
Is it right to share videos like this?
https://drive.google.com/file/d/13TczGFS_QSjRw5AYfdZ_xOzrVMp8sFaV/view?usp=drivesdk

**Comment by LetheRegina** [comment]
Your access request has been accepted. It's my first time to allow Google drive sharing. Please tell me if you can't see the video.

**Comment by hippogamesunity** [comment]
Thanks! What's your app version? From Menu/About.

**Comment by LetheRegina** [comment]
Version : 4.44 Latest
It's the latest version. Because I deleted it and downloaded it again.

**Comment by hippogamesunity** [comment]
Please share the Pixel Studio folder on your Google Drive to hippogamesunity@gmail.com, I'll check your files.

**Comment by LetheRegina** [comment]
I shared it. I hope I can get my paintings back.

**Comment by hippogamesunity** [comment]
Many thanks, this will be fixed in the next update. As a workaround, you can open PSP in any text editor and replace
`"Version":1,"TileMode":false`
with
`"Version":2,"TileMode":false`

**Comment by LetheRegina** [comment]
Thank you. I'm glad I found my painting.
