### ISSUE TITLE
Issue with color codes

### ISSUE THREAD

**Issue by hippogamesunity** [hippogamesunity/PixelStudioHub#16]
Hello guys, every time I add a color to a new palette the color suffers minimal changes, for example, I put #00FFA8 in palette but it auto-modifies to #00FFA7. That's a really big problem, at lears for me, fix it, please!

**Comment by Bearroneous** [comment]
Hi, yes I have had this too. I'll try to set something to a specific number, eg RGB 40,40,40, and when i check it again its like 39,39,39. Thanks for looking into it.

**Comment by hippogamesunity** [comment]
This was fixed a long time ago.
