### ISSUE TITLE
The New Update Scrambled The Editing Interface

### ISSUE THREAD

**Issue by StereoMadnessss** [hippogamesunity/PixelStudioHub#163]
I have no clue why this change was made, but I am completely infuriated. I tried rolling back the update, and attempting to deal with using it in this state, but it’s completely unusable for me. At this point if another wrong move like this is made again, I will go and find something else like Krita or Aseprite. Please add the option to revert the interface changes as they are really confusing and I do not like them at all.

**Comment by hippogamesunity** [comment]
Hi, you can set you tools in Settings/Tools.
