### ISSUE TITLE
Can’t upload to Pixel Network

### ISSUE THREAD

**Issue by Otakuscott** [hippogamesunity/PixelStudioHub#168]
I’m trying to upload art I created in the basic Pixel Studio to Pixel Network but it gives me the error message “Pixel Network is for pixel art only. Your image doesn’t meet pixel art criteria (maximum 256 colors.” I made the image using Pixel Studio and it has wayyyyy less than 256 colors so I have no idea what it’s talking about.
![051A9338-E527-4064-91A4-718B814F9165](https://user-images.githubusercontent.com/132094826/235221543-fea8953d-6b54-4568-bd01-b6c4e6c59c0c.jpeg)
![BDF759F6-0248-4492-83A0-FC777AC641AA](https://user-images.githubusercontent.com/132094826/235221547-cdcfd3f5-9c0b-4387-aea1-4b861e39d416.png)

**Comment by hippogamesunity** [comment]
Hi, your image is JPEG, it's a lossy format that introduces new colors.

**Comment by Otakuscott** [comment]
I’ve tried saving it as different formats, but it still won’t accept it.

**Comment by hippogamesunity** [comment]
Try Functions/Quantize colors.

**Comment by Otakuscott** [comment]
Thank you
