### ISSUE TITLE
FEATURE REQUEST   rotate 45 degrees

### ISSUE THREAD

**Issue by captnhanky** [hippogamesunity/PixelStudioHub#17]
First of all: thank you for answering my feature request for pixel studio.
Some critics: 
You answered me 2 MONTHS after I posted it in a wrong thread just to tell me I am in the wrong application thread. Without an answer of the question..You did not even move my question to here! 

Ok, rant over.

Please support 45 degree rotation for smoother animation.

Thanks!

**Comment by hippogamesunity** [comment]
Rotation was added to Selection Tools popup.
