### ISSUE TITLE
[Android] Why not export to Image folder?

### ISSUE THREAD

**Issue by anggaaryas** [hippogamesunity/PixelStudioHub#181]
It is more convenient and easy to access than save to app scope folder. My suggestion is , when user save to image extension (.png , .jpg) , save to image folder.

**Comment by hippogamesunity** [comment]
Hello, you can use Save to Photos/Files option for this.

сб, 6 янв. 2024 г., 10:47 Angga Arya Saputra ***@***.***>:

**Comment by anggaaryas** [comment]
Oh it s in 3 dot save menu. OK
