### ISSUE TITLE
Problem related to the purchase of pro version

### ISSUE THREAD

**Issue by Cruvo** [hippogamesunity/PixelStudioHub#186]
I have been trying to purchase the pro version on my pixel studio which i downloaded from steam but its not showing neither the price nor the purchase button, its staying just like this, what to do, if its like that then could you send me the details of the package

![image](https://github.com/hippogamesunity/PixelStudioHub/assets/93931124/67ba444e-ad98-4a85-9f68-e908cf166bf2)

**Comment by hippogamesunity** [comment]
Hello! Try to force close Steam, restart it and then open Pixel Studio.

**Comment by Cruvo** [comment]
@hippogamesunity

**Comment by Cruvo** [comment]
Yeah it worked, btw what's the difference between pro and pro cross?

**Comment by hippogamesunity** [comment]
Great! https://github.com/hippogamesunity/PixelStudioHub/wiki/Cross-platform-PRO
