### ISSUE TITLE
Bug Report: missing artworks and Profile Picture

### ISSUE THREAD

**Issue by Ramsfin** [hippogamesunity/PixelStudioHub#188]
Bug Report: Missing Artworks and Profile Picture

Hi,
I am experiencing an issue where my artwork and profile picture have disappeared. Although the counter shows I have 21 artworks, only 7 are visible.

Steps to Reproduce:

Log into Pixel Studio.
Navigate to "profile."
Counter shows 21 artworks, but only 7 are visible.
Expected Behavior:
All 21 artworks and my profile picture should be displayed.

Actual Behavior:
Only 7 artworks are visible, and my profile picture is missing.

I am using PC version of Pixle Studio.

version: 4.93 beta 

Please assist in resolving this issue. Thank you.

Best regards,

RAMSFIN

![Screenshot (60)](https://github.com/hippogamesunity/PixelStudioHub/assets/172992768/596e1c9b-1086-49e8-a868-8a9acdb1df2a)

![Screenshot (61)](https://github.com/hippogamesunity/PixelStudioHub/assets/172992768/2710ecfc-631f-47de-be0a-fd03f6addbd3)

**Comment by hippogamesunity** [comment]
Hello! Sorry, there was an incident with a lack of storage, and some unpopular and large files were deleted.
