### ISSUE TITLE
when I saved my artwork, I enlarged to avoid blurring. now, it's saying the file is too big for the free version

### ISSUE THREAD

**Issue by Nerdaderp** [hippogamesunity/PixelStudioHub#192]

**Comment by hippogamesunity** [comment]
Hello, please learn how bilinear filtering works. In short, you do not need to upscale when saving. To load your initial project, load its' tab or check Backup folder in Storage.

**Comment by Nerdaderp** [comment]
This artwork took me over 30 hours of work, I need to have access to it for a school project. the canvas was originally 400x400 and I upscaled it to 1600x1600. I was not aware of this beforehand, but I need to have access to it. is there any way to fix this problem?

**Comment by Nerdaderp** [comment]
The backup of my drawing is almost an hour behind what the final product is, so using a back up file isn't an option.

**Comment by hippogamesunity** [comment]
If it was PNG, you can open and downscale it with any photo editor. Did you check tabs? Did you close the tab?
