### ISSUE TITLE
Hello, please learn how bilinear filtering works. In short, you do not need to upscale when saving. To load your initial project, load its' tab or check Backup folder in Storage.

### ISSUE THREAD

**Issue by Nerdaderp** [hippogamesunity/PixelStudioHub#193]
Hello, please learn how bilinear filtering works. In short, you do not need to upscale when saving. To load your initial project, load its' tab or check Backup folder in Storage.

_Originally posted by @hippogamesunity in https://github.com/hippogamesunity/PixelStudioHub/issues/192#issuecomment-2397656846_
             
The backup is much behind my final product, all I need is to be able to scale my artwork back down to 800x800

**Comment by hippogamesunity** [comment]
The Free version can't open files larger than 1024x1024, I'm not sure if I can help you with this, sorry. Load from Backup or Tabs, or use any photo editor to downscale PNG.
