### ISSUE TITLE
Google Drive FAQ

### ISSUE THREAD

**Issue by VeilleurTrytoFix** [hippogamesunity/PixelStudioHub#194]
hi,
cant understand how google drive backup works, everytime i press "Google Drive Sync" nothing happen and my file is not backup on my drive folder
i have also tried to save my project locally and press "Google drive Sync", nothing happend only "Scanning ... Complete" but no file arrived in google Drive Folder 

i have only 2 files inside  UserSprites.json and UserBrushes.json

can you add in the FAQ the correct process to use Google Drive Backup for files ?

Thanks

**Comment by hippogamesunity** [comment]
Hello! Does Pixel Studio folder exist on your Google Drive?

**Comment by VeilleurTrytoFix** [comment]
Yes, i can see 2 files inside UserSprites.json and UserBrushes.json

**Comment by hippogamesunity** [comment]
Do you use subfolders inside Storage?

**Comment by VeilleurTrytoFix** [comment]
No

**Comment by VeilleurTrytoFix** [comment]
i deleted folder on google drive, empty trash, resync from pixel studio and it works. Thanks

**Comment by hippogamesunity** [comment]
Glad to hear this, good luck!
