### ISSUE TITLE
Steam + Google Account

### ISSUE THREAD

**Issue by softplaceio** [hippogamesunity/PixelStudioHub#195]
Hello,
I bought Pixel Studio Pro Cross at my Android smartphone.
Now in the morning I found that Pixel Studio is available on Steam (Linux) + Proton.
I downloaded Pixel Studio and tried to log in using my Google account. For some reason I can not access.
What should I do to authenticate?

I have Windows 10 environment and installed Steam and Pixel Studio. Everything happened well to authenticate with my Google account. When I changed the topic to the dark said it needs to be license pro. But I already bought license to cross.

**Comment by hippogamesunity** [comment]
Hello! What is your login in Pixel Network?
Did you check this article? https://github.com/hippogamesunity/PixelStudioHub/wiki/Restore-purchases

**Comment by softplaceio** [comment]
> Hello! What is your login in Pixel Network? Did you check this article? https://github.com/hippogamesunity/PixelStudioHub/wiki/Restore-purchases

Thanks a lot!
Solved!
