### ISSUE TITLE
Need to convert files to pixel studio files

### ISSUE THREAD

**Issue by Vortetty** [hippogamesunity/PixelStudioHub#2]
I have a file with a ton of 16*16 images and need to convert them to ps files

**Comment by hippogamesunity** [comment]
Hi! Do you mean you need spritesheet export?

**Comment by Vortetty** [comment]
sure? i just need to get every minecraft texture into the editor files

**Comment by hippogamesunity** [comment]
Please attach an example.

**Comment by Vortetty** [comment]
Those all need to become editable
And keep that file structure

On Wed, Aug 1, 2018, 7:27 AM Arick House <vortetty@hotmail.com<mailto:vortetty@hotmail.com>> wrote:

On Tue, Jul 31, 2018, 11:26 PM Nate River <notifications@github.com<mailto:notifications@github.com>> wrote:
Please attach an example.

**Comment by hippogamesunity** [comment]
I see nothing, sorry.

**Comment by Vortetty** [comment]
it did not attatch, i need to convert a ton of png files into pixel station files basically


On Wed, Aug 1, 2018 at 10:19 AM Nate River <notifications@github.com<mailto:notifications@github.com>> wrote:

I see nothing, sorry.

**Comment by hippogamesunity** [comment]
Hm, what is your scenario? I can't understand what you want? It seems like some kind of automation?
