### ISSUE TITLE
Saving Project Issue

### ISSUE THREAD

**Issue by denvfreitas** [hippogamesunity/PixelStudioHub#21]
I can't save my project. It's a .psp, 0.18 seconds/90 frames, 311x233 resolution project. When I try saving it, the application is forced to stop. Luckily, autosave always keep my project backed up, but the problem is that I can't convert it to .gif or .mp4.

I have a samsung tablet and a zenfone 3, tried saving it on both and it didn't work.

Please, I hope you can help me. If any information is needed, I'll be happy to help.

**Comment by hippogamesunity** [comment]
Hi! Please send me your psp.

**Comment by Redoutebeuls** [comment]
Hi 
I can't save ! I have to stop the app on my iMac cause I can't do anything else when I try to save

**Comment by Redoutebeuls** [comment]
As u see on the screen capture... I can't do anything !

**Comment by hippogamesunity** [comment]
So the app freezes/crashes when you press PSP? Or just when this windows pops up? 90 frames of 311x233 resolution should be a problem for Mac.

**Comment by Redoutebeuls** [comment]
Thanx for your response.
Yes it crashes for all type of files. even PNG Gif...

**Comment by hippogamesunity** [comment]
But when you reopen the app everything works fine, right? You can draw and play the animation?

**Comment by Redoutebeuls** [comment]
yes
