### ISSUE TITLE
Unable to restore purchase

### ISSUE THREAD

**Issue by Jake593** [hippogamesunity/PixelStudioHub#23]
I upgraded to “BRO” status on my iPhone. But when I try to restore my purchase on my iPad nothing happens. The purchase button works fine tho. I tried closing the app and deleting and reinstalling it but it’s still not working.

**Comment by hippogamesunity** [comment]
Hi! If it was Bro on sale, try restoring it on next sale.

пт, 21 июн. 2019 г., 7:10 Jake593 <notifications@github.com>:
