### ISSUE TITLE
Feature Request: Aseprite export

### ISSUE THREAD

**Issue by scotticles** [hippogamesunity/PixelStudioHub#24]
Would love to see an export to .aseprite file format. I like to use my phone to start my pixels and then would be great to touch up in aseprite.
https://github.com/aseprite/aseprite/blob/master/docs/ase-file-specs.md

**Comment by hippogamesunity** [comment]
Hi! I'm not sure if benefits of this will cover large amount of work required. So I'm focused on more important features, sorry.
