### ISSUE TITLE
How do I export a colour from the canvas to the palette?

### ISSUE THREAD

**Issue by dertrutinator** [hippogamesunity/PixelStudioHub#26]
How can I pick a colour using the pipette tool and save it to the palette? I've tried selecting a colour in the palette while the colour picker was opened, but that didn't work. I also thought I might be able to use the pipette from the colour picker, but it was greyed out. I read through the wiki entry for _palette_, but I could not find out how to do this. Because of this I had to manually copy the colour codes to new colours in order to save them. If there is no feature for doing this more easily, please consider this a feature request.

On a related note, what are the arrows in the colour picker used for? Each time I press them, I just get an _Array index out of bounds_ error.

**Comment by hippogamesunity** [comment]
Hi! You can copy/paste a hex code. Since update 1.47 there will be the pipette icon in color picker.
You can move colors in the Palette with arrow. Sometimes it throws exception, this also will be fixed in 1.47.
