### ISSUE TITLE
Error when connecting to Google Drive

### ISSUE THREAD

**Issue by mobyjames** [hippogamesunity/PixelStudioHub#27]
I love the idea of sync'ing work between iPad and my macbook, but I get the following error on OS X when I tap the Drive icon.

<img width="1392" alt="Screen Shot 2019-10-01 at 2 39 09 PM" src="https://user-images.githubusercontent.com/1327007/66002884-91bfd000-e459-11e9-9402-809e762ee803.png">

**Comment by hippogamesunity** [comment]
Hi! I will try to fix this, thanks for reporting!

**Comment by hippogamesunity** [comment]
Fixed in 1.87.
