### ISSUE TITLE
Files Lost

### ISSUE THREAD

**Issue by btshz** [hippogamesunity/PixelStudioHub#30]
All the drawings I've made and saved are gone. I was getting ready to work on a previous piece and when I went to open it they were all gone. And I'm not sure why. I know for sure that I saved then all and they were once all there and I could open and close them.
I also looked through the files on my phone and they are there but for some reason I cant open them. It says the files are not supported by any apps I use but they were literally created on this app so i dont understand??

**Comment by hippogamesunity** [comment]
Hello! Please make a video as I don't understand what happens. Files are lost and at the same time they exist, looks really strange.

**Comment by btshz** [comment]
> Hello! Please make a video as I don't understand what happens. Files are lost and at the same time they exist, looks really strange.

Okay so I screen recorded it once but it didn't come out great so I was going to do it again and the second time I did it all the files that I couldnt find suddenly appeared.... so problem solved I guess??? Not sure what happened. Thanks for trying to help though I really appreciate it!

**Comment by hippogamesunity** [comment]
Hm) Good luck. You know how to reach me)
