### ISSUE TITLE
I paid 5€ to get nothing. also everything stopped working!

### ISSUE THREAD

**Issue by mervangrande** [hippogamesunity/PixelStudioHub#32]
after a while, in the middle of my work, the utensils stopped working. I couldn't erase things oder draw things. I restarted it like 5 times and it always worked for only 2 minutes. I hate it so much! I want my money back. all that work for nothing...

**Comment by hippogamesunity** [comment]
Hi! What version do you use and what is your device? Also please attach
your receipt.

сб, 22 февр. 2020 г., 14:21 mervangrande <notifications@github.com>:
