### ISSUE TITLE
I cannot save png files

### ISSUE THREAD

**Issue by ffekete** [hippogamesunity/PixelStudioHub#33]
![image](https://user-images.githubusercontent.com/3746703/75759055-d8796500-5d2c-11ea-93d2-867ae7417bc7.png)
This is what i see, what caused this?

**Comment by hippogamesunity** [comment]
Hi! Thanks, I'll fix it as soon as possible.

**Comment by hippogamesunity** [comment]
Can you confirm it worked in previous version please?

**Comment by ffekete** [comment]
Yes, it stopped working today, i guess the version was updated today/yesterday to the latest one.
Thanks for looking into it!

**Comment by ffekete** [comment]
It is still working on my phone (android), but no on my mac.

**Comment by ffekete** [comment]
Hmm, this is working now, and i received a notification that the app is updating, i guess this was the root cause, somehow the update went wrong first?
