### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by X-Boy742** [hippogamesunity/PixelStudioHub#36]
![Screenshot_20200326-120534_Pixel Studio](https://user-images.githubusercontent.com/62628616/77713482-dd88a780-6fac-11ea-9973-16d5bc894691.jpg)
I tried adding an image, it only popped up for that specific one...

**Comment by hippogamesunity** [comment]
Hi! Can you reproduce the error? If so, please provide detailed steps.

**Comment by X-Boy742** [comment]
I tried following in my steps, and I realised I used an unsupported image type.

**Comment by X-Boy742** [comment]
Thanks for the support, even if not a lot
