### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sjptop** [hippogamesunity/PixelStudioHub#41]
When i open my animated pixel art and touch author on comment and go back, I got this error!
![Screenshot_20200504-155519_Pixel Studio](https://user-images.githubusercontent.com/64770579/80942849-d1e89600-8e20-11ea-945f-b5e48f5c15bd.jpg)
![Screenshot_20200504-155418_Pixel Studio](https://user-images.githubusercontent.com/64770579/80942861-d6ad4a00-8e20-11ea-9c05-24c301a9dd76.jpg)
![Screenshot_20200501-122834_Pixel Studio](https://user-images.githubusercontent.com/64770579/80942917-f3498200-8e20-11ea-8197-7ef55f75cb6b.jpg)

**Comment by hippogamesunity** [comment]
Hi! Please wait for the next update.

пн, 4 мая 2020 г., 10:05 sjptop <notifications@github.com>:

**Comment by sjptop** [comment]
And i found more bugs!
when I open my pixel art and touch author on comment, and go back, I found that it is changed to another pixel art!

**Comment by sjptop** [comment]
And I foung even more bug! When I open my pixel art and tuoch my profile in comment and i open the pixel art, I got this.
![Screenshot_20200505-123159_Pixel Studio](https://user-images.githubusercontent.com/64770579/81032888-7bd12c80-8ecc-11ea-8886-f3d47ab78ad3.jpg)
![Screenshot_20200505-123021_Pixel Studio](https://user-images.githubusercontent.com/64770579/81032897-8390d100-8ecc-11ea-9e4b-1c60712cb6d7.jpg)
![Screenshot_20200505-122626_Pixel Studio](https://user-images.githubusercontent.com/64770579/81032905-8986b200-8ecc-11ea-9807-9cfb9c06f5ff.jpg)
![Screenshot_20200504-161017_Pixel Studio](https://user-images.githubusercontent.com/64770579/81032909-8ab7df00-8ecc-11ea-8922-aefe58f7b08b.jpg)
![Screenshot_20200505-122613_Pixel Studio](https://user-images.githubusercontent.com/64770579/81032913-8b507580-8ecc-11ea-9906-59a6b41184d7.jpg)
