### ISSUE TITLE
Pressure sensitivity

### ISSUE THREAD

**Issue by brentorama** [hippogamesunity/PixelStudioHub#44]
if you please.
Control over radius and opacity.

This software is wonderful.

**Comment by AMathGamez** [comment]
Not sure what you are trying to say here buddy, can you be a bit more specific? Maybe I can help :)

**Comment by brentorama** [comment]
Pressure sensitivity. For us users with tablets or note phones. Your
painting tools should support pressure input. Hard press increases the
pressure value. Pressure value can be mapped to the radius of the stamp or
the opacity with user control. At the very least, paint and erase should
offer support for pressure sensitivity.

**Comment by hippogamesunity** [comment]
Implemented.
