### ISSUE TITLE
App opens briefly then crashes on iPad Pro

### ISSUE THREAD

**Issue by symbiat** [hippogamesunity/PixelStudioHub#49]
First time install, first open, app crashes and disappears after startup logo appears briefly. I’m on iPad Pro 11” running iOS 13.5.1.

**Comment by lotts243** [comment]
I’m having the same issue!

**Comment by hippogamesunity** [comment]
Hello! I've made some possible solution in 2.84, I'll remind you when it will be released.

**Comment by hippogamesunity** [comment]
Can you check 2.84 build please?

**Comment by lotts243** [comment]
It’s working now! Thankyou!

Sent from my iPhone

On 5 Jul 2020, at 09:33, Nate River <notifications@github.com> wrote:

﻿

Can you check 2.84 build please?
