### ISSUE TITLE
Copy visible option

### ISSUE THREAD

**Issue by Noofbiz** [hippogamesunity/PixelStudioHub#52]
Hello! I love pixel studio and use it a bit. One thing I would love is to be able to copy all the visible pixels to a buffer rather than just the ones on the selected layer. I make my objects as separate animation frames to get just one sprite sheet for them. However, I also like to copy/paste them into bigger scenes like rooms. When it’s a single image it’s easy, just use add image. When I have multiple frames, add image only works with the first animation frame, so I have to either merge all my layers (boo) or copy and paste it layer by layer. An option to copy visible would be perfect!

**Comment by hippogamesunity** [comment]
Hi! Do you mean you need Copy Frame as a Single Image feature?

**Comment by Noofbiz** [comment]
Just something that could copy all visible pixels to the buffer rather than the selected layer, but that would work too

**Comment by hippogamesunity** [comment]
I'll think about this in the next update, thanks.

пн, 17 авг. 2020 г. в 23:28, Noofbiz <notifications@github.com>:

**Comment by hippogamesunity** [comment]
3.01

**Comment by Noofbiz** [comment]
Thanks! Works perfect!
