### ISSUE TITLE
Google Authorization Error

### ISSUE THREAD

**Issue by peterhodgden** [hippogamesunity/PixelStudioHub#53]
I am having issues syncing my google drive to my local files in Pixel Studio for iOS in iPhone 11 Pro Max. After selecting the google drive sync button, a notifications prompts me with the following:

"'Pixel Studio' wants to use
'google.com' to Sign In
This allows the app and website to
share information about you."

After selecting "Continue", I'm am redirected to a webpage that says the following:

"Google
Authorization Error
Error 400: redirect_uri_mismatch"

Because of this error, I am unable to sync my local workspace with my google drive. I only want to use this app if I can also use this feature.

Help me please!

- I've tried resetting my phone
- I've tried deleting the app and re-downloading
- I've tried signing out of my google account on Safari and signing back in
- I've tried adding my google account to the "Passwords and Accounts" page in the Settings app

None of those fixed my issue.

**Comment by hippogamesunity** [comment]
Hello. Does it happen now?
