### ISSUE TITLE
I can’t open file and backup at Google Drive

### ISSUE THREAD

**Issue by hitomi-obb** [hippogamesunity/PixelStudioHub#54]
Hello.

I can’t open my one file after App(ver.PRO)

First, I tried to delete app & safari cash, also to restarted iPad & app.
And I delete some pixel art on App but I can’t open the file. I can open many files besides this.
But it forced termination when it open part of it(first attached file).

Also, I can’t backup my file at Google Drive. I saw this(two attached files) red screen.

I worry about eternally can’t open it. I didn’t backup. So I will be disappear if you don’t give me solution because spend a of of time for my art (;_;)
Please help me!

![8C9A30FF-B893-4B81-A6E2-9F9A8A2B0BA7](https://user-images.githubusercontent.com/70462508/91655385-20feb900-eaeb-11ea-93a4-a6e5bb5df7fa.png)
![214395B2-408F-4F3E-BB7D-FF64B925CA80](https://user-images.githubusercontent.com/70462508/91655388-26f49a00-eaeb-11ea-83a3-b24c6e676989.png)
![F5F50BEF-8401-4917-88CE-D6BC8E58F2B6](https://user-images.githubusercontent.com/70462508/91655389-2825c700-eaeb-11ea-8b2d-caff55816359.png)

**Comment by Giff1** [comment]
I’m also having the same issue. I deleted the app and reinstalling it and now all of my work is gone. I had the majority of it backed up through Drive but I can’t get the stuff I worked on today back. I also paid for the pro version.

**Comment by hitomi-obb** [comment]
Year, also I didn’t backup file, so I desperately want to backup it! I don’t want to delete App(;_;)

**Comment by hippogamesunity** [comment]
Fixed.
