### ISSUE TITLE
Reference image resize undo does not work and is easy to trigger

### ISSUE THREAD

**Issue by mjeppesen** [hippogamesunity/PixelStudioHub#57]
When using a image as a backgroundreference, it is easy (on iPad) to accidentally resize the reference image via a two finger pinch if the layer is selected, meaning that the drawing no longer is overlaid on the reference. Locking the layer does not prevent resize, which I imagine is also a bug.  Pressing undo undoes drawing but does not undo the image resize.

**Comment by hippogamesunity** [comment]
Hello, Reference is a part of a frame, it doesn't have its' own history and is not affected by Layer settings. It's by design and I'm not sure if I could fix this in the near future, sorry.
