### ISSUE TITLE
Unable to open .ase file

### ISSUE THREAD

**Issue by schnumy** [hippogamesunity/PixelStudioHub#59]
I am unable to open the attached .ase files from disk and received the attached error - EndOfStreamException...

[20201013-PixelStudio-EndOfStreamException](https://user-images.githubusercontent.com/67377121/95891369-48e96980-0d85-11eb-8082-ff9bf6bb8c64.png)

[Colour pack.zip](https://github.com/hippogamesunity/PixelStudioHub/files/5372875/Colour.pack.zip)

**Comment by hippogamesunity** [comment]
Hello! Thank, I've alredy registered this issue in the 3rd party asset hub: https://github.com/martinhodler/unity-aseprite-importer/issues/33
