### ISSUE TITLE
Tile Preview

### ISSUE THREAD

**Issue by MintL** [hippogamesunity/PixelStudioHub#6]
I would love to have a way to visualize how my tile would look like repeated all over the screen. In that way I can fix my edges to look better. See picture! 
![screen shot 2018-08-17 at 15 14 46](https://user-images.githubusercontent.com/508683/44271605-e34bd200-a23a-11e8-80c1-0f2c506fc0fa.png)

**Comment by hippogamesunity** [comment]
Hi! PS has Tile Mode now, and you can disable canvas movement restriction to get what you want.
