### ISSUE TITLE
Can’t delete files or access other functions in gallery

### ISSUE THREAD

**Issue by otterwillow** [hippogamesunity/PixelStudioHub#63]
Hi, 
I cannot press the ‘...’ button in the storage/gallery. The app says ‘Unavailable at this moment, please try again later.’ when I try. I have opened and closed the app multiple times and the issue persists.

I am on iOS 14.2 using an iPad. I am on version 3.16 of pixel studio.

![983B1787-F4B5-4EA9-AA27-306E1FBBF82F](https://user-images.githubusercontent.com/27446643/101676680-63715380-3a53-11eb-8341-3e3a03bd53f6.png)

**Comment by PhilMinecraft** [comment]
We have a same conditions
https://github.com/hippogamesunity/PixelStudioHub/issues/64

**Comment by hippogamesunity** [comment]
Fixed.
