### ISSUE TITLE
iPad frequent crashing

### ISSUE THREAD

**Issue by sladesladeslade** [hippogamesunity/PixelStudioHub#65]
Hi not sure if there is already a known crash bug. I have an iPad Air (App Store says everything is compatible and both the app and iPad are updated to latest version). No other apps have an issue.

The app crashes very frequently. It seems to be random, but sometimes happens when I press buttons. It happens as frequently as every 30 seconds to a minute. I’ve tried reinstalling and restarting and nothing is fixing it. The app just closes on its own. (Free version)

**Comment by hippogamesunity** [comment]
Fixed.
