### ISSUE TITLE
Strange error message. (Frame #0 contains more than 256 colors!)

### ISSUE THREAD

**Issue by HidetoKoudanshi** [hippogamesunity/PixelStudioHub#74]
I can’t save my animated GIF due to this weird error I can’t fix. What do I do?

![84B13112-27A7-42F8-AD84-709CF04D93F5](https://user-images.githubusercontent.com/9960438/120137807-1f117580-c1a3-11eb-8583-f44c6f3b0017.png)

**Comment by hippogamesunity** [comment]
Hi, you can apply 8-bit colors from Functions.
