### ISSUE TITLE
.msi, .exe or .zip installer, for those with no steam or win10

### ISSUE THREAD

**Issue by atesin** [hippogamesunity/PixelStudioHub#76]
i don't use windows10 (bloated) or steam (dont like drm) .... also, it hurts my stomach to sign up and install an 800mb app (steam) just to install a 90mb app

i want to use your app to learn games developing, but i couldn't find where to download directly

**Comment by hippogamesunity** [comment]
Unfortunately, we don't have another distribution channels.
