### ISSUE TITLE
How do I reactivate my Pro Version??

### ISSUE THREAD

**Issue by rischhart** [hippogamesunity/PixelStudioHub#78]
I've bought the Pro version of Pixelstudio previously on Android via the Google Play Store and wanted to ask if there was a way to reactivate it on Windows...? Pls help

**Comment by hippogamesunity** [comment]
Hello!
https://github.com/hippogamesunity/PixelStudioHub/wiki/Restore-purchases
https://github.com/hippogamesunity/PixelStudioHub/wiki/Cross-platform-PRO
