### ISSUE TITLE
any command line tools for converting between PSP and other files?

### ISSUE THREAD

**Issue by Eli-the-Bearded** [hippogamesunity/PixelStudioHub#81]
I've been using Pixel Studio Pro to draw tiles. Then to create an image with the tile repeated I have to resave as PNG before I can use my command line tools to make an N x M tiled version. A command line tool (or source code for one, I can compile stuff) would be handy.

I've examined the file format, but it looks like I'd need good documentation about how the actions in the `_historyJson` work before I could write one myself. The `_source` and `_snapshot` arrays sadly do not appear to be the bitmap in some raw form.

**Comment by hippogamesunity** [comment]
Hello! Unfortunately, PSP is not a public format, although it's just a JSON.
About tile option - most game engines has Time Mode feature for Images, so there is no need to create large tiled textures.
I think the best option for you is requesting a new feature for saving tiles inside Pixel Studio.

**Comment by Eli-the-Bearded** [comment]
I'm not working with any game engines. Last time I drew pixel art for a game was the 1980s. I'm just doing stuff for my fun. I don't quite know what your "save as tile" would do. Just as an example, working from a 1x scale 64x64 tile saved as PNG:

```
$ pngtopnm grided-07-23-2021.png |
  pnmtile $(( 64*12 )) $(( 64 *6 )) |
  pnmenlarge 3 |
  pnmtopng > ../mine/grided-07-23-2021_6x12.png 
```

https://qaz.wtf/tmp/grided-07-23-2021_6x12.png

I do this sort of thing on my phone (Termux shell on Android).

If "Save as PPM" or "Save as PAM" is an enhancement you'll consider, I'll request that. Those are _trivial_ formats to read and write (by design).

http://netpbm.sourceforge.net/doc/pam.html

**Comment by hippogamesunity** [comment]
Unfortunately, I'm not planning to add PAM format support as it's a very, very specific feature for just you and maybe a few another people.

**Comment by hippogamesunity** [comment]
But I'll consider making 'Tiling' option to generate tiled texture of desired size.

**Comment by Eli-the-Bearded** [comment]
Understood. Those are obscure formats.
