### ISSUE TITLE
Tiling feature request

### ISSUE THREAD

**Issue by Eli-the-Bearded** [hippogamesunity/PixelStudioHub#82]
Outcome of discussion in https://github.com/hippogamesunity/PixelStudioHub/issues/81

Please add a feature to make an image that is another image tiled. Eg, I have drawn a 16x16 pattern, and then at New Image
creation, I could specify a 150x90 image and have it pre-filled with a the 16x16 design, cropped for the final partial row and column.

**Comment by hippogamesunity** [comment]
Hi! You can achieve this with the following way:
- create a tiled sprite (16x16 for example)
- save it
- add it as a new brush in Brushe tool options
- create a new large texture (256x256 for example)
- select your brush and check Tiling option
- fill your texture and save

Please let me know if it was helpful for you!
