### ISSUE TITLE
help with files

### ISSUE THREAD

**Issue by pabillidge** [hippogamesunity/PixelStudioHub#85]
first of all, thank you for your hard work on the Pixel Studio sofware. it's amazing. But I'm having trouble to open the files that I saved as PSP. I can see that they are in the folder, but when I try to open them the file that is open it is always the last work I've done, so I can't access the others that I want to continue. So it's like I can't save a work half way to come back to it later if I started another. can someone help me with this please?

**Comment by hippogamesunity** [comment]
Hi! Make sure the app is up to date. Also try moving files to the app storage if possible and open them inside the app.

**Comment by pabillidge** [comment]
> Hi! Make sure the app is up to date. Also try moving files to the app storage if possible and open them inside the app.

Thanks, that also apply for the PC version?

**Comment by hippogamesunity** [comment]
'Open As' feature doesn't work for UWP, but works on Steam version.
