### ISSUE TITLE
Can't login to Pixel Studio

### ISSUE THREAD

**Issue by storm1971** [hippogamesunity/PixelStudioHub#86]
Getting a SSL CA Certificate error when trying to login with Google Play to access my Gallery.

Please Help
Rbfakstorm

About a month ago I was the guy who you helped get back on the Pixel Network. But this wasn't the same problem. I know your 7 hrs ahead of me from Chicago to Serbia so as of this text your time should be 10:32pm

**Comment by hippogamesunity** [comment]
Fixed.
