### ISSUE TITLE
Playing with UISupportsDocumentBrowser feature on iOS

### ISSUE THREAD

**Issue by hippogamesunity** [hippogamesunity/PixelStudioHub#87]
Well, in context of Pixel Studio. There are 3 options for saving/opening files: the internal app folder (Application.persistentDataPath), Files and Photos (using yasirkula's assets). The first option is most popular btw. Everything works fine, but there are some inconveniences for users:
1) User files in Application.persistentDataPath are deleted when the app is deleted, that's very bad
2) Users can't explore Application.persistentDataPath with Files (as it's hidden very deep by the OS)

So, I'm playing with adding UISupportsDocumentBrowser to info.plist.
With this feature enabled, iOS makes a public Documents folder for the app located at the top like "On IPad/Pixel Studio".
Users can easily access it with the Files app, and it's great.
This looks just like a shortcut for the internal app folder, and all files saved to Application.persistentDataPath appear in  "On IPad/Pixel Studio" (including some Unity's service files, unfortunately).

The first question - is it possible to move/save/link this folder to iCloud? So user files stay after Pixel Studio is deleted.

And the second problem with UISupportsDocumentBrowser is:
- is UISupportsDocumentBrowser is set to NO, if user selects a file from Files and opens it with Pixel Studio, the app is launched with Application.absoluteURL like file:///private/var/mobile/Containers/Data/Application/CAF48A8C-5217-4898-A85F-92E76688AF8F/tmp/com.PixelStudio-Inbox/Race.psx
It looks that iOS just copies the selected file from a public location to Application.persistentDataPath/tmp, and Unity app can read it.
- after enabling UISupportsDocumentBrowser, Application.absoluteURL becomes like file:///private/var/mobile/Containers/Shared/AppGroup/38F34BE3-B14B-4232-B484-12914C21A471/File%20Provider%20Storage/Race.psx, and Unity app can't read this. The file is not copied anymore, and the link is security-scoped URL (NSURL Class Reference).

So the second question - how to read files by the such security-scoped URL given? Because I want to leave UISupportsDocumentBrowser feature as it's very convenient for users.

**Comment by yasirkula** [comment]
I honestly don't know but you should give the solutions I've suggested a try.
