### ISSUE TITLE
Cross platform PRO Android/Mac

### ISSUE THREAD

**Issue by honzasusek** [hippogamesunity/PixelStudioHub#89]
I just bought the cross-platform PRO upgrade on Android with the intention of having it sync with my Mac, however when I try to activate the PRO version on the computer through Pixel Network, I can't even see the little black "pro" chip by my account name as I do on mobile. Tried logging on and off repeatedly on both devices, but nothing seems to change.

**Comment by honzasusek** [comment]
@hippogamesunity any tips on how to resolve? do I have to wait for the update?

**Comment by hippogamesunity** [comment]
You already have PRO, but this black label will appear after a new update
will be published.

чт, 21 окт. 2021 г. в 10:13, Honza Susek ***@***.***>:
