### ISSUE TITLE
Question about Pro

### ISSUE THREAD

**Issue by AndyKitty8** [hippogamesunity/PixelStudioHub#92]
Is Single Platform Pro a one-time purchase or recurring subscription?

**Comment by hippogamesunity** [comment]
Hello, it's a durable purchase.

**Comment by AndyKitty8** [comment]
Do you mean recurring? As in I’d be charged monthly?

**Comment by hippogamesunity** [comment]
It's not a subscription, it's one-time payment.

**Comment by AndyKitty8** [comment]
Ok thank you
