### ISSUE TITLE
After latest update, app won’t open beyond load

### ISSUE THREAD

**Issue by Gunrian** [hippogamesunity/PixelStudioHub#95]
I’m a very happy paying customer, who absolutely love this app. BUT after the latest app & software update… The app opens up with the colorful PS logo, And then the app turns black, and nothing happens…. Please fix it asap!. All the best T.

**Comment by hippogamesunity** [comment]
Hi, what is your device? Did you try reinstalling?

**Comment by Gunrian** [comment]
I did that, and it worked. But all the files I had not google drive synced, was lost :(.
Any way to find them again?
Thank you for your reply.

**Comment by hippogamesunity** [comment]
You didn't provide any info about your device and platform, so I hope this may help you
https://github.com/hippogamesunity/PixelStudioHub/wiki/Locating-files
