### ISSUE TITLE
Can't Open The App Anymore

### ISSUE THREAD

**Issue by monsterdust** [hippogamesunity/PixelStudioHub#97]
I don't know why, but since this morning I have been unable to open the app. I'm on iOS and I've even tried deleting and redownloading.

**Comment by hippogamesunity** [comment]
Hi! This will be fixed in 3.72. As a workaround, you can update to iOS 15.

**Comment by monsterdust** [comment]
> Hi! This will be fixed in 3.72. As a workaround, you can update to iOS 15.

Thank you! Sorry about that, my phone didn't alert me that there was an iOS update
