### ISSUE TITLE
App only works on ipad IOS 15 now

### ISSUE THREAD

**Issue by woofmaster** [hippogamesunity/PixelStudioHub#98]
This may be intended but posting this in case someone else has this issue.

On older versions of Pixel Studio you just see the splash screen and then the whole ipad goes black and returns to the desktop - no error message.  Tried closing the app and restarting the ipad.

Tried this on IOS 14.8, 14.81 and an older Ipad air. (same issue on multiple networks and ipads)

Only starting working once I updated to IOS 15.1

**Comment by hippogamesunity** [comment]
Hub/issues/97

**Comment by hippogamesunity** [comment]
https://github.com/hippogamesunity/PixelStudioHub/issues/97

**Comment by Run-009** [comment]
This is the same with iPhone. App does not open on IOS 14
